config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "products#index"
  
  resources :products, only: [:index, :show] do
    post :add_to_cart, on: :member
    post :remove_from_cart, on: :member
    post :adjust_item, on: :member
  end
  
  resource :cart
  
  resources :orders do
    post :checkout_spgateway, on: :member
  end

  post "spgateway/return"
  post "spgateway/notify"

  namespace :admin do
    root "products#index"
    resources :products
    resources :orders
  end

end

app/views/shared/_cart.html.erb
<div class="col-lg-3">
  <h1 class="my-4">Shop Cart</h1>
  <hr>
   <div class="item-list">
      <% current_cart.cart_items.each do |item| %>
      <%= render partial: "shared/item", locals: { item: item } %>
      <% end %>
    </div>
    <hr>
    <div class="subtotal">
      <p>Subtotal</p>
      <p class="ammount"><%= current_cart.subtotal %></p>          
    </div>
    <%= link_to "View Cart", cart_path %>
</div>

app/views/shared/_form_error.html.erb
<% if object.errors.any? %>
  <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

app/views/shared/_item.html.erb
<div class="cart-item product-<%= item.product.id %>">
  <%= image_tag item.product.image %>
  <div class="cart-item-info">
    <h3><%= item.product.name %></h3>
    $ <%= item.product.price %><br>
    <div class="cart-item-adjust">
      <%= link_to '+', adjust_item_product_path(item.product, type: "add"), method: :post, remote: true %>
      <span class="cart-<%= item.product.id %>-qty" ><%= item.quantity %></span>
      <%= link_to '-', adjust_item_product_path(item.product, type: "substract"), method: :post, remote: true %>
      <%= button_to "Detele", remove_from_cart_product_path(item.product), remote: true %>
    </div>
  </div>
</div>