config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "products#index"
  
  resources :products, only: [:index, :show] do
    post :add_to_cart, on: :member
    post :remove_from_cart, on: :member
    post :adjust_item, on: :member
  end
  
  resource :cart
  
  resources :orders do
    post :checkout_spgateway, on: :member
  end

  post "spgateway/return"
  post "spgateway/notify"

  namespace :admin do
    root "products#index"
    resources :products
    resources :orders
  end

end

app/models/order.rb
class Order < ApplicationRecord
  validates_presence_of :name, :address, :phone, :payment_status, :shipping_status

  belongs_to :user
  has_many :order_items, dependent: :destroy
  has_many :products, through: :order_items
  has_many :payments

  # set constant to generate select options
  PAYMENT_STATUS = [
    ["Not Paid", :not_paid],
    ["Paid", :paid]
  ]

  SHIPPING_STATUS = [
    ["Not Shipped", :not_shipped],
    ["Shipped",:shipped]
  ]

  def add_order_items(cart)
    cart.cart_items.each do |item|
      self.order_items.build(
        product_id: item.product.id,
        quantity: item.quantity,
        price: item.product.price
      )
    end
  end

  def subtotal
    order_items.map{ |x| x.item_total }.sum
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::AdminController
  def index
    @orders = Order.all
  end

  def edit
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    if @order.update(order_params)
      if @order.shipping_status == "shipped"
        # UserMailer.notify_order_shipped(@order).deliver_now
      end
      if @order.payment_status == "paid"
        # UserMailer.notify_order_paid(@order).deliver_now
      end
      redirect_to admin_orders_path, notice: "Order updated"
    else
      flash.now[:alert] = @order.errors.full_messages.to_sentence
      render "admin/orders/edit"
    end
  end

  private

  def order_params
    params.require(:order).permit(:payment_status, :shipping_status)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = current_user.orders.order(created_at: :desc)
  end

  def create
    # manually check if user logged in
    if current_user.nil?
      # store order data in session so we can retrieve it later
      session[:new_order_data] = params[:order]
      # redirect to devise login page
      redirect_to new_user_session_path
    else
      @order = current_user.orders.new(order_params)
      @order.sn = Time.now.to_i
      @order.add_order_items(current_cart)
      @order.amount = current_cart.subtotal
      if @order.save
        current_cart.destroy
        session.delete(:new_order_data)
        # UserMailer.notify_order_create(@order).deliver_now!
        redirect_to orders_path, notice: "new order created"
      else
        @items = current_cart.cart_items
        render "carts/show"
      end
    end
  end

  def update
    @order = current_user.orders.find(params[:id])
    if @order.shipping_status == "not_shipped"
      @order.shipping_status = "cancelled"
      @order.save
      redirect_to orders_path, alert: "order##{@order.sn} cancelled."
    end
  end

  def checkout_spgateway
    @order = current_user.orders.find(params[:id])
    if @order.payment_status != "not_paid"
      flash[:alert] = "Order has been paid."
      redirect_to orders_path
    else
      @payment = Payment.create!(
        sn: Time.now.to_i,
        order_id: @order.id,
        payment_method: params[:payment_method],
        amount: @order.amount
      )

      render layout: false
    end
  end

  private

  def order_params
    params.require(:order).permit(:name, :phone, :address, :payment_method)
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/checkout_spgateway.html.erb
<h1>轉址前往信用卡付款頁面，請勿關閉或離開頁面...</h1>

<form action="<%= Spgateway.url %>" method="post">
  <% Spgateway.new(@payment).generate_form_data(spgateway_return_url).each do |key, value| %>
    <%= hidden_field_tag key, value %>
  <% end %>
  <input type="submit" style="visibility:hidden;">
</form>

<script>document.forms[0].submit()</script>

app/views/orders/index.html.erb
<% @orders.each do |order| %>
  <div class="panel panel-order">
    <h2>Order # <%= order.sn %></h2>
    <div class="order-content">
      <div class="right-border">
        <div class="order-data">
          <ul class="order-list">
            <% order.order_items.each do |item| %>
            <li><%= item.product.name %> <%= item.quantity %> x <%= item.price %></li>
            <% end %>
            <hr>
            Subtotal <%= order.subtotal %>
          </ul>
        </div>
        <div>
          <h2>Shipping Information</h2>
          <div class="order-data">
            <%= order.name %>, <%= order.phone %>, <%= order.address %>
          </div>
        </div>
      </div>
      <div class="order-data">
        <p>Payment Status: <%= order.payment_status %></p>
        <p>Shipping Status: <%= order.shipping_status %></p>
        <% if order.payment_status == "not_paid" && order.shipping_status != "cancelled" %>
          <% Payment::PAYMENT_METHODS.each do |method| %>
            <%= link_to method, checkout_spgateway_order_path(order, payment_method: method), method: :post, class: "btn" %> 
          <% end %>
        <% end %>

        <% if order.shipping_status == "not_shipped" %>
          <%= link_to "Cancel Order", order_path(order), method: :patch, class: "btn"  %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>