config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "products#index"
  
  resources :products, only: [:index, :show] do
    post :add_to_cart, on: :member
    post :remove_from_cart, on: :member
    post :adjust_item, on: :member
  end
  
  resource :cart
  
  resources :orders do
    post :checkout_spgateway, on: :member
  end

  post "spgateway/return"
  post "spgateway/notify"

  namespace :admin do
    root "products#index"
    resources :products
    resources :orders
  end

end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, presence: true
  validates :price, presence: true

  has_many :cart_items, dependent: :destroy
  has_many :carts, through: :cart_items
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::AdminController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.page(params[:page]).per(15)
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to admin_products_path, notice: "product was successfully created"
    else
      render :new
    end
  end

  def update
    if @product.update(product_params)
      redirect_to admin_product_path(@product), notice: "product was successfully updated"
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to admin_products_path, alert: "product was deleted"
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :description, :price, :image)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.page(params[:page]).per(50)
  end

  def show
    @product = Product.find(params[:id])
  end

  def add_to_cart
    @product = Product.find(params[:id])
    current_cart.add_cart_item(@product)
  end

  def remove_from_cart
    @product = Product.find(params[:id])
    cart_item = current_cart.cart_items.find_by(product_id: @product)
    cart_item.destroy
  end

  def adjust_item
    @product = Product.find(params[:id])
    cart_item = current_cart.cart_items.find_by(product_id: @product)
    if params[:type] == "add"
      cart_item.quantity += 1
    elsif params[:type] == "substract"
      cart_item.quantity -= 1
    end

    if cart_item.quantity == 0
      cart_item.destroy
    else
      cart_item.save
    end
    
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_product.html.erb
<h2><%= action_name.capitalize %> Product </h2>

<%= render partial: "shared/form_error", locals: { object: @product }%>

<%= form_for [:admin, @product] do |f| %>
  <div class="">
    <%= f.text_field :name, placeholder: "Product Name" %>
  </div>
  <div class="">
    <%= image_tag(@product.image, width: 200) if @product.image? %>
    <%= f.file_field :image %>
  </div>
  <div class="">
    <%= f.text_area :description, placeholder: "Add Product Description" %>
  </div>
  <div class="">
    <%= f.number_field :price, placeholder: "$" %>
  </div>
  <%= f.submit %>
<% end %>

app/views/admin/products/edit.html.erb
<%= render 'product' %>

app/views/admin/products/index.html.erb
<%= link_to "Add New Product", new_admin_product_path %>

<table>
  <tr>
    <th>Product Name</th>
    <th>Image</th>
    <th>Price</th>
    <th>Option</th>
  </tr>
  <% @products.each do |product| %>
    <tr>
      <td><%= product.name %></td>
      <td><%= image_tag(product.image, width: 50) if product.image? %></td>
      <td><%= product.price %></td>
      <td><%= link_to "Edit Detail", edit_admin_product_path(product) %></td>
      <td><%= link_to "Delete", admin_product_path(product), method: :delete %></td>
    </tr>
  <% end %>
</table>

<%= paginate @products %>

app/views/admin/products/new.html.erb
<%= render 'product' %>